-- Tests for emberline.state module
local M = {}

function M.run()
  local state = require("emberline.state")

  describe("emberline.state", function()
    -- Reset state before each describe block
    state.reset()

    describe("add_buffer()", function()
      it("adds buffer to the list", function()
        state.reset()
        state.add_buffer(1)
        local buffers = state.get_buffers()
        expect(#buffers).to_equal(1)
        expect(buffers[1]).to_equal(1)
      end)

      it("maintains insertion order", function()
        state.reset()
        state.add_buffer(1)
        state.add_buffer(2)
        state.add_buffer(3)
        local buffers = state.get_buffers()
        expect(buffers[1]).to_equal(1)
        expect(buffers[2]).to_equal(2)
        expect(buffers[3]).to_equal(3)
      end)

      it("does not add duplicate buffers", function()
        state.reset()
        state.add_buffer(1)
        state.add_buffer(1)
        local buffers = state.get_buffers()
        expect(#buffers).to_equal(1)
      end)
    end)

    describe("remove_buffer()", function()
      it("removes buffer from list", function()
        state.reset()
        state.add_buffer(1)
        state.add_buffer(2)
        state.remove_buffer(1)
        local buffers = state.get_buffers()
        expect(#buffers).to_equal(1)
        expect(buffers[1]).to_equal(2)
      end)

      it("handles removing non-existent buffer", function()
        state.reset()
        state.add_buffer(1)
        state.remove_buffer(999)
        local buffers = state.get_buffers()
        expect(#buffers).to_equal(1)
      end)
    end)

    describe("get_buffers()", function()
      it("returns ordered list of buffers", function()
        state.reset()
        state.add_buffer(5)
        state.add_buffer(3)
        state.add_buffer(7)
        local buffers = state.get_buffers()
        expect(buffers[1]).to_equal(5)
        expect(buffers[2]).to_equal(3)
        expect(buffers[3]).to_equal(7)
      end)

      it("returns empty table when no buffers", function()
        state.reset()
        local buffers = state.get_buffers()
        expect(#buffers).to_equal(0)
      end)
    end)

    describe("move_buffer()", function()
      it("moves buffer left in list", function()
        state.reset()
        state.add_buffer(1)
        state.add_buffer(2)
        state.add_buffer(3)
        state.move_buffer(2, -1) -- Move buffer 2 left
        local buffers = state.get_buffers()
        expect(buffers[1]).to_equal(2)
        expect(buffers[2]).to_equal(1)
        expect(buffers[3]).to_equal(3)
      end)

      it("moves buffer right in list", function()
        state.reset()
        state.add_buffer(1)
        state.add_buffer(2)
        state.add_buffer(3)
        state.move_buffer(2, 1) -- Move buffer 2 right
        local buffers = state.get_buffers()
        expect(buffers[1]).to_equal(1)
        expect(buffers[2]).to_equal(3)
        expect(buffers[3]).to_equal(2)
      end)

      it("does not move past boundaries", function()
        state.reset()
        state.add_buffer(1)
        state.add_buffer(2)
        state.move_buffer(1, -1) -- Try to move first buffer left
        local buffers = state.get_buffers()
        expect(buffers[1]).to_equal(1)
        expect(buffers[2]).to_equal(2)
      end)
    end)

    describe("toggle_pin()", function()
      it("pins an unpinned buffer", function()
        state.reset()
        state.add_buffer(1)
        state.toggle_pin(1)
        local data = state.get_data(1)
        expect(data.pinned).to_be_truthy()
      end)

      it("unpins a pinned buffer", function()
        state.reset()
        state.add_buffer(1)
        state.toggle_pin(1)
        state.toggle_pin(1)
        local data = state.get_data(1)
        expect(data.pinned).to_be_falsy()
      end)
    end)

    describe("sort_pins_to_left()", function()
      it("moves pinned buffers to the left", function()
        state.reset()
        state.add_buffer(1)
        state.add_buffer(2)
        state.add_buffer(3)
        state.toggle_pin(3) -- Pin buffer 3
        state.sort_pins_to_left()
        local buffers = state.get_buffers()
        expect(buffers[1]).to_equal(3) -- Pinned buffer should be first
      end)

      it("maintains order among pinned buffers", function()
        state.reset()
        state.add_buffer(1)
        state.add_buffer(2)
        state.add_buffer(3)
        state.toggle_pin(3)
        state.toggle_pin(1)
        state.sort_pins_to_left()
        local buffers = state.get_buffers()
        -- Both 1 and 3 are pinned, should maintain their relative order
        local pinned_indices = {}
        for i, bufnr in ipairs(buffers) do
          local data = state.get_data(bufnr)
          if data.pinned then
            table.insert(pinned_indices, bufnr)
          end
        end
        expect(#pinned_indices).to_equal(2)
      end)

      it("maintains order among unpinned buffers", function()
        state.reset()
        state.add_buffer(1)
        state.add_buffer(2)
        state.add_buffer(3)
        state.toggle_pin(2)
        state.sort_pins_to_left()
        local buffers = state.get_buffers()
        expect(buffers[1]).to_equal(2) -- Pinned
        -- Unpinned buffers should maintain their relative order
        expect(buffers[2]).to_equal(1)
        expect(buffers[3]).to_equal(3)
      end)
    end)

    describe("get_data()", function()
      it("returns buffer metadata", function()
        state.reset()
        state.add_buffer(1)
        local data = state.get_data(1)
        expect(data).to_be_type("table")
        expect(data.pinned ~= nil).to_be_truthy()
      end)

      it("returns nil for unknown buffer", function()
        state.reset()
        local data = state.get_data(999)
        expect(data).to_be_nil()
      end)

      it("tracks modified state", function()
        state.reset()
        state.add_buffer(1)
        state.set_modified(1, true)
        local data = state.get_data(1)
        expect(data.modified).to_be_truthy()
      end)
    end)

    describe("set_name()", function()
      it("sets buffer display name", function()
        state.reset()
        state.add_buffer(1)
        state.set_name(1, "test.lua")
        local data = state.get_data(1)
        expect(data.name).to_equal("test.lua")
      end)
    end)

    describe("get_index()", function()
      it("returns buffer position in list", function()
        state.reset()
        state.add_buffer(5)
        state.add_buffer(10)
        state.add_buffer(15)
        expect(state.get_index(5)).to_equal(1)
        expect(state.get_index(10)).to_equal(2)
        expect(state.get_index(15)).to_equal(3)
      end)

      it("returns nil for buffer not in list", function()
        state.reset()
        expect(state.get_index(999)).to_be_nil()
      end)
    end)

    describe("get_buffer_at()", function()
      it("returns buffer at given position", function()
        state.reset()
        state.add_buffer(5)
        state.add_buffer(10)
        expect(state.get_buffer_at(1)).to_equal(5)
        expect(state.get_buffer_at(2)).to_equal(10)
      end)

      it("returns nil for out of bounds position", function()
        state.reset()
        state.add_buffer(1)
        expect(state.get_buffer_at(0)).to_be_nil()
        expect(state.get_buffer_at(99)).to_be_nil()
      end)
    end)
  end)
end

return M
