local M = {}
function M.setup()
  local keymap = vim.keymap
  keymap.set('n', 'Q', '<Nop>', { noremap = true, silent = true })
  keymap.set("v", "J", ":m '>+1<CR>gv=gv", { desc = "Move lines down", silent = true })
  keymap.set("v", "K", ":m '<-2<CR>gv=gv", { desc = "Move lines up", silent = true })
  keymap.set('i', '<CR>', function()
    return vim.fn.pumvisible() == 1 and '<C-y>' or '<CR>'
  end, { expr = true, silent = true, desc = 'Accept completion or newline' })
  keymap.set('i', '<C-e>', '<C-e>', { desc = 'Close completion menu', silent = true })
  keymap.set('n', '<leader>wh', '<C-w>h', { desc = 'Go to left window', silent = true })
  keymap.set('n', '<leader>wj', '<C-w>j', { desc = 'Go to lower window', silent = true })
  keymap.set('n', '<leader>wk', '<C-w>k', { desc = 'Go to upper window', silent = true })
  keymap.set('n', '<leader>wl', '<C-w>l', { desc = 'Go to right window', silent = true })
  keymap.set('n', '<leader>ws', '<C-w>s', { desc = 'Split horizontal', silent = true })
  keymap.set('n', '<leader>wv', '<C-w>v', { desc = 'Split vertical', silent = true })
  keymap.set('n', '<leader>wc', '<C-w>c', { desc = 'Close window', silent = true })
  keymap.set('n', '<leader>wo', '<C-w>o', { desc = 'Close other windows', silent = true })
  keymap.set('n', '<leader>w=', '<C-w>=', { desc = 'Equalize windows', silent = true })
  keymap.set('n', '<leader>qq', ':qa<CR>', { desc = 'Quit all', silent = true })
  keymap.set('n', '<leader>qw', ':wqa<CR>', { desc = 'Save and quit all', silent = true })
  keymap.set('n', '<leader>qf', ':qa!<CR>', { desc = 'Force quit', silent = true })
  keymap.set('n', '<leader>qs', ':w<CR>', { desc = 'Save file', silent = true })
  keymap.set('n', '<leader>xx', ':copen<CR>', { desc = 'Open quickfix', silent = true })
  keymap.set('n', '<leader>xl', ':lopen<CR>', { desc = 'Open location list', silent = true })
  keymap.set('n', '<leader>xn', ':cnext<CR>', { desc = 'Next quickfix', silent = true })
  keymap.set('n', '<leader>xp', ':cprev<CR>', { desc = 'Previous quickfix', silent = true })
  keymap.set('n', '<leader>tn', function()
    vim.opt.relativenumber = not vim.opt.relativenumber:get()
  end, { desc = 'Toggle relative numbers', silent = true })
  keymap.set('n', '<leader>tw', function()
    vim.opt.wrap = not vim.opt.wrap:get()
  end, { desc = 'Toggle word wrap', silent = true })
  keymap.set('n', '<leader>uH', ':nohlsearch<CR>', { desc = 'Clear search highlight', silent = true })
end
return M
